name: openfoodfacts_flutter_lints_example
description: A project that showcases how to use the OFF Flutter lints.
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dev_dependencies:
  openfoodfacts_flutter_lints:
    path: ../
